- name: Security guide
  displayName: overview, summary, introduction, get started
  href: security/index.md
- name: Core terminology
  displayName: terms
  href: security/glossary.md
- name: Get signed-in identity
  href: security/how-to-get-signed-in-identity.md
- name: Create managed identities
  displayName: principals
  href: security/how-to-create-managed-identities.md
- name: Disable key-based authentication
  displayName: key, ropc, connection string
  href: security/how-to-disable-key-based-authentication.md
- name: Grant control plane access
  href: security/how-to-grant-control-plane-role-based-access.md
- name: Grant data plane access
  href: security/how-to-grant-data-plane-role-based-access.md
- name: Reference
  items:
    - name: Control plane
      displayName: example, permissions, rbac, role, definition
      items:
        - name: Actions
          href: /azure/role-based-access-control/permissions/databases?context=/azure/cosmos-db/nosql/context/context#microsoftdocumentdb
        - name: Built-in roles
          href: /azure/role-based-access-control/built-in-roles?context=/azure/cosmos-db/nosql/context/context#databases
    - name: Data plane
      displayName: example, permissions, rbac, role, definition, dataActions
      items:
        - name: Actions
          href: security/reference-data-plane-actions.md
        - name: Built-in roles
          href: security/reference-data-plane-roles.md
    - name: Frequently asked questions
      displayName: faq, questions, answers
      href: faq.yml?context=/azure/cosmos-db/nosql/context/context#security
